#///The (!) symbol means "info"\\\#

#======== Gradle properties ========#
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = true
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.configuration-cache = true

#======= Parchment version ========#
parchment_mappings_version = 2024.11.17

#======== NeoForge version ========#
neo_version = 21.1.249

#======= Minecraft version =======#
minecraft_version = 1.21.1

#======== Mod loader version ========#
#(!)///Wide mod loader version range\\\#
loader_version_range = [21.1.200,)
fml_loader_version_range = [4,)

#======== Mod info ========#
mod_id = ccanimatronics
mod_name = CC Animatronics
mod_license = MIT
mod_author = antocoslev
mod_description = Bring your world to life with our Lua programmable animatronics !
mod_version = 1.0.0
mod_group_id = com.antocoslev.ccanimatronics

#======== Create version ========#
create_version = [6.0.0,)

#======== ComputerCraft version ========#
computercraft_version = [1.112.0,)

#======== Simulated version ========#
simulated_version = [1.3.0,)
